// GENERATED by scripts/t3tls_gen_fixtures.sh (t_94ee6012) — do not edit.
// Throwaway EC P-256 self-signed identities for the TLS TOFU-pinning tests.
// Test fixtures only; never used for production traffic.
import Foundation
import Security

enum TLSFixtureIdentities {
    /// The legitimate gateway's synthetic cert and matching P-256 test key.
    static let gatewayPrivateKeyX963 = Data(base64Encoded: "BO3hVW8FW9WBFkj9ub7a5JdmyczezvMnVsuDky6MLzj5NeDHaeDQuF3sEVM//pH46yhc8zSh+oMPqaNejIhMxzg3xd79NqdfpEwbrUQBSQBo7bDV3sD4uL1K6680ZBS4oQ==")!
    static let gatewayCertificateDER = Data(base64Encoded: "MIIBVzCB/aADAgECAgkA+oIUXbGapFUwCgYIKoZIzj0EAwIwITEfMB0GA1UEAwwWaGVybWVzLWdhdGV3YXktZml4dHVyZTAeFw0yNjA5MjQwNzM3MjlaFw00NjA5MTkwNzM3MjlaMCExHzAdBgNVBAMMFmhlcm1lcy1nYXRld2F5LWZpeHR1cmUwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATt4VVvBVvVgRZI/bm+2uSXZsnM3s7zJ1bLg5MujC84+TXgx2ng0Lhd7BFTP/6R+OsoXPM0ofqDD6mjXoyITMc4ox4wHDAaBgNVHREEEzARhwR/AAABgglsb2NhbGhvc3QwCgYIKoZIzj0EAwIDSQAwRgIhAIkRUZslTUw+15Yr2qYlN0Zx2jSzWH7X15hFAa5r+9YfAiEAiixZ5EBqlmJjMVCo7RQJpnFoqxkCilGa8DTJfiXk4RE=")!
    /// SPKI SHA-256 base64 of the gateway cert (openssl-computed reference).
    static let gatewaySPKIBase64 = "cVHgL9Z89Wbfc7y4S2AypmccSjn5Ac89WLNwSN37zAI="

    /// A different self-signed identity (the MITM / replaced-cert actor).
    static let mitmPrivateKeyX963 = Data(base64Encoded: "BFzrHoLTHrPIgUSnckW1WiUQN0pzm3V1GttmeWFXyfFKDKdqx9gOjZxQ+7/kkM2zruPqT1M0BQNYppQnStRKU2JmW79XV6RRStsl2VvJVAIHcMglKhYNrJFp7lmmtVSwKg==")!
    static let mitmCertificateDER = Data(base64Encoded: "MIIBVDCB+6ADAgECAgkAnZ+WG7pufoYwCgYIKoZIzj0EAwIwIDEeMBwGA1UEAwwVbWl0bS1hdHRhY2tlci1maXh0dXJlMB4XDTI2MDkyNDA3MzcyOVoXDTQ2MDkxOTA3MzcyOVowIDEeMBwGA1UEAwwVbWl0bS1hdHRhY2tlci1maXh0dXJlMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEXOsegtMes8iBRKdyRbVaJRA3SnObdXUa22Z5YVfJ8UoMp2rH2A6NnFD7v+SQzbOu4+pPUzQFA1imlCdK1EpTYqMeMBwwGgYDVR0RBBMwEYcEfwAAAYIJbG9jYWxob3N0MAoGCCqGSM49BAMCA0gAMEUCIGQDPnmUB8gQQYuLMCN+xFPS91GsYaXw31euII59FObKAiEAxBAjnn0BA19NcqBufT3WAbnfNlGySojtUfI7ADHQc54=")!
    static let mitmSPKIBase64 = "LYL7REqnjTKYyow+f600rSb/RY5lhZTfh/n8cvyb5Xw="

    /// A certificate with an UNSUPPORTED key type (RSA-1024) — the extractor
    /// must fail closed on it.
    static let weakCertificateDER = Data(base64Encoded: "MIIB4DCCAUmgAwIBAgIJAIwJ9ss8EoArMA0GCSqGSIb3DQEBCwUAMCIxIDAeBgNVBAMMF3Vuc3VwcG9ydGVkLWtleS1maXh0dXJlMB4XDTI2MDkyNDA3MzcyOVoXDTQ2MDkxOTA3MzcyOVowIjEgMB4GA1UEAwwXdW5zdXBwb3J0ZWQta2V5LWZpeHR1cmUwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBALmfxaGRy7KlSZlVoH3sNZOfxpT9kf2dfD0bFyBkQJhRX5mN2MqcHki6QIMcpVWQZpmlmCVjbbkv6LyQN6x2iT5ABk3nzmZRNo93GDu2F29eh63eZF/F/SnU92rvLe8r8+75UuFbzKVs8pdjWWF95E4b9yQly56YxRFfcBtxZ6GvAgMBAAGjHjAcMBoGA1UdEQQTMBGHBH8AAAGCCWxvY2FsaG9zdDANBgkqhkiG9w0BAQsFAAOBgQBYac+EMOVdFpTmC4v97uKw8E7qvP5/5KHqFpTngEDGd4Ub/+5xf9nTLoSeI+4nOA6Ytx8TB9qINa86nr1+h5ICYDJOzaupCMT4Z4vP/DSpsvXEavgXP9+k8WWvBvgxCaE1fCnxHJdxuHV7pvo30LLbxBQJMxN11qc0PqGVJJe08A==")!

    /// Pair the synthetic certificate with an in-memory software key. This
    /// keeps TLS signing out of SecurityServer/keychain-backed identities.
    static func identity(certificateDER: Data, privateKeyX963: Data) throws -> SecIdentity {
        guard let certificate = SecCertificateCreateWithData(nil, certificateDER as CFData) else {
            throw NSError(domain: "TLSFixture", code: 4,
                          userInfo: [NSLocalizedDescriptionKey: "certificate fixture could not be created"])
        }
        let attributes: [String: Any] = [
            kSecAttrKeyType as String: kSecAttrKeyTypeECSECPrimeRandom,
            kSecAttrKeyClass as String: kSecAttrKeyClassPrivate,
            kSecAttrKeySizeInBits as String: 256,
            kSecAttrIsPermanent as String: false,
        ]
        var keyError: Unmanaged<CFError>?
        guard let privateKey = SecKeyCreateWithData(privateKeyX963 as CFData, attributes as CFDictionary, &keyError) else {
            throw keyError?.takeRetainedValue() ?? NSError(
                domain: "TLSFixture", code: 5,
                userInfo: [NSLocalizedDescriptionKey: "private key fixture could not be created"])
        }
        guard let identity = SecIdentityCreate(nil, certificate, privateKey) else {
            throw NSError(domain: "TLSFixture", code: 6,
                          userInfo: [NSLocalizedDescriptionKey: "certificate and private key do not match"])
        }
        return identity
    }
}
