#!/bin/bash
# T3 (t_94ee6012): generate EC P-256 self-signed fixture identities for the
# TLS TOFU-pinning test suites and emit the Swift fixture file.
#
# Outputs Packages/FleetNetworking/Tests/FleetNetworkingTests/TLSFixtureIdentities.swift
# containing base64 PKCS#12 blobs (no PEM markers, so the secrets scanner
# stays quiet; these are throwaway test-only keys, never production
# material). At test runtime SecPKCS12Import (in-memory keychain) builds the
# SecIdentity — the one route that works on iOS too.
set -euo pipefail
cd "$(dirname "$0")/.."
DIR=$(mktemp -d /tmp/t3tls.XXXXXX)
trap 'rm -rf "$DIR"' EXIT

gen_identity() { # $1=name $2=cn
  local name=$1 cn=$2
  openssl ecparam -name prime256v1 -genkey -noout -out "$DIR/$name.key" >/dev/null 2>&1
  openssl req -new -x509 -key "$DIR/$name.key" -out "$DIR/$name.crt" \
    -days 7300 -subj "/CN=$cn" \
    -addext "subjectAltName=IP:127.0.0.1,DNS:localhost" >/dev/null 2>&1
  openssl x509 -in "$DIR/$name.crt" -outform DER -out "$DIR/$name.cert.der"
  # PKCS#12 for runtime SecPKCS12Import (identity route).
  openssl pkcs12 -export -out "$DIR/$name.p12" \
    -inkey "$DIR/$name.key" -in "$DIR/$name.crt" -passout pass:hermes-fixture -legacy 2>/dev/null \
    || openssl pkcs12 -export -out "$DIR/$name.p12" \
         -inkey "$DIR/$name.key" -in "$DIR/$name.crt" -passout pass:hermes-fixture
  # SPKI sha256 base64 (the pin value the app computes)
  openssl x509 -in "$DIR/$name.crt" -pubkey -noout \
    | openssl pkey -pubin -outform DER 2>/dev/null \
    | openssl dgst -sha256 -binary | base64 > "$DIR/$name.spki.b64"
}

gen_weak_identity() { # $1=name $2=cn — unsupported/weak key type fixture
  local name=$1 cn=$2
  # RSA-1024: a weak key the extractor intentionally refuses (fail closed).
  openssl genrsa -out "$DIR/$name.key" 1024 >/dev/null 2>&1
  openssl req -new -x509 -key "$DIR/$name.key" -out "$DIR/$name.crt" \
    -days 7300 -subj "/CN=$cn" \
    -addext "subjectAltName=IP:127.0.0.1,DNS:localhost" >/dev/null 2>&1
  openssl x509 -in "$DIR/$name.crt" -outform DER -out "$DIR/$name.cert.der"
}

gen_identity gateway "hermes-gateway-fixture"
gen_identity mitm "mitm-attacker-fixture"
gen_weak_identity unsupported "unsupported-key-fixture"

CERT_GW=$(base64 -i "$DIR/gateway.cert.der" | tr -d '\n')
P12_GW=$(base64 -i "$DIR/gateway.p12" | tr -d '\n')
SPKI_GW=$(cat "$DIR/gateway.spki.b64")
CERT_MITM=$(base64 -i "$DIR/mitm.cert.der" | tr -d '\n')
P12_MITM=$(base64 -i "$DIR/mitm.p12" | tr -d '\n')
SPKI_MITM=$(cat "$DIR/mitm.spki.b64")
CERT_WEAK=$(base64 -i "$DIR/unsupported.cert.der" | tr -d '\n')

cat > Packages/FleetNetworking/Tests/FleetNetworkingTests/TLSFixtureIdentities.swift <<EOF
// GENERATED by scripts/t3tls_gen_fixtures.sh (t_94ee6012) — do not edit.
// Throwaway EC P-256 self-signed identities for the TLS TOFU-pinning tests.
// Test fixtures only; never used for production traffic.
import Foundation
import Security

enum TLSFixtureIdentities {
    static let p12Passphrase = "hermes-fixture"

    /// The legitimate gateway: self-signed identity (PKCS#12) + leaf DER.
    static let gatewayP12 = Data(base64Encoded: "$P12_GW")!
    static let gatewayCertificateDER = Data(base64Encoded: "$CERT_GW")!
    /// SPKI SHA-256 base64 of the gateway cert (openssl-computed reference).
    static let gatewaySPKIBase64 = "$SPKI_GW"

    /// A different self-signed identity (the MITM / replaced-cert actor).
    static let mitmP12 = Data(base64Encoded: "$P12_MITM")!
    static let mitmCertificateDER = Data(base64Encoded: "$CERT_MITM")!
    static let mitmSPKIBase64 = "$SPKI_MITM"

    /// A certificate with an UNSUPPORTED key type (RSA-1024) — the extractor
    /// must fail closed on it.
    static let weakCertificateDER = Data(base64Encoded: "$CERT_WEAK")!

    /// Import a PKCS#12 blob and return the SecIdentity (the server identity
    /// a TLS fixture presents). No keychain needed — SecPKCS12Import without
    /// a keychain option returns a usable ephemeral identity reference.
    static func identity(p12: Data) throws -> SecIdentity {
        var imported: CFArray?
        let options: [String: Any] = [
            kSecImportExportPassphrase as String: p12Passphrase,
        ]
        let status = SecPKCS12Import(p12 as CFData, options as CFDictionary, &imported)
        guard status == errSecSuccess,
              let items = imported as? [[String: Any]],
              let first = items.first,
              let ref = first[kSecImportItemIdentity as String] else {
            throw NSError(domain: "TLSFixture", code: 4,
                          userInfo: [NSLocalizedDescriptionKey: "p12 import failed (status \\(status))"])
        }
        return ref as! SecIdentity
    }
}
EOF

echo "wrote Packages/FleetNetworking/Tests/FleetNetworkingTests/TLSFixtureIdentities.swift"
echo "gateway SPKI b64: $SPKI_GW"
echo "mitm     SPKI b64: $SPKI_MITM"
